name: CI/CD Pipeline for Azure Function App

on:
  push:
    branches:
      - main  # Change to your default branch

permissions:
  id-token: write
  contents: read

env:
  AZURE_FUNCTION_APP_NAME: "WAQASCanadaCentral"  # Your Azure Function App name
  COSMOS_DB_ENDPOINT: ${{ secrets.COSMOS_DB_ENDPOINT }}
  COSMOS_DB_KEY: ${{ secrets.COSMOS_DB_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Use your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MyFunction/requirements.txt

      - name: Run tests
        run: |
          # Set the environment variables directly for the test run
          echo "COSMOS_DB_ENDPOINT=${{ secrets.COSMOS_DB_ENDPOINT }}" >> $GITHUB_ENV
          echo "COSMOS_DB_KEY=${{ secrets.COSMOS_DB_KEY }}" >> $GITHUB_ENV
          python -m pytest MyFunction/test  # Adjust the path as needed

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_SECRET }}

      - name: Deploy to Azure Function App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_FUNCTION_APP_NAME }}
          package: WAQASCanadaCentral # Path to the function app directory

      - name: Logout from Azure
        run: az logout
