name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies  
      run: |
        python -m pip install --upgrade pip
        pip install -r MyFunction/requirements.txt

    - name: Run tests
      run: |
        python -m pytest MyFunction/test    

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure
      run: |
        az deployment group create --resource-group ResourceWaqas --template-file Infrastructure/merged_template.json --parameters @Infrastructure/merged_parameters.json

